### ISSUE TITLE
Issue with a combination of this and Mortal Enemies

### ISSUE THREAD

**Issue by mrudat** [Synthesis-Collective/RaceCompatibilityDialogue#11]
https://discord.com/channels/759302581448474626/805950403828908103/825778093348225064

**Comment by mrudat** [comment]
Can't seem to reproduce with:
SkyrimSE + USSEP + RaceCompatibility + Race Compatibility USKP Override + INIGO + ACatsLife + Mortal Enemies + Mortal Enemies patcher + Race Compatability Dialog patcher

**Comment by TwistedModding** [comment]
i ended up figuring this out, you can close this... It was something to do with the order of my patchers...
