### ISSUE TITLE
Getting this error when I add this to synthasis

### ISSUE THREAD

**Issue by Madpaddy** [Synthesis-Collective/RaceCompatibilityDialogue#12]
Program.cs(66,39): error CS1503: Argument 1: cannot convert from 'Mutagen.Bethesda.Plugins.Order.ILoadOrder<Mutagen.Bethesda.Plugins.Order.IModListing<Mutagen.Bethesda.Skyrim.ISkyrimModGetter>>' to 'Mutagen.Bethesda.Plugins.Order.LoadOrder<Mutagen.Bethesda.Plugins.Order.IModListing<Mutagen.Bethesda.Skyrim.ISkyrimModGetter>>'
Program.cs(66,39): error CS1503: Argument 1: cannot convert from 'Mutagen.Bethesda.Plugins.Order.ILoadOrder<Mutagen.Bethesda.Plugins.Order.IModListing<Mutagen.Bethesda.Skyrim.ISkyrimModGetter>>' to 'Mutagen.Bethesda.Plugins.Order.LoadOrder<Mutagen.Bethesda.Plugins.Order.IModListing<Mutagen.Bethesda.Skyrim.ISkyrimModGetter>>'

**Comment by Noggog** [comment]
This is typically how that's dealt with:
https://github.com/Mutagen-Modding/Synthesis/discussions/168

but I also just upgraded it to latest versions, so it should be happy again now anyway

**Comment by Madpaddy** [comment]
Thank you all working now...
