### ISSUE TITLE
Some dialogue conditions not using correct "Run on" flag

### ISSUE THREAD

**Issue by HDMFanatic** [Synthesis-Collective/RaceCompatibilityDialogue#14]
I'm seeing that there are a number of flags that don't copy properly when using this patcher.

Target, CombatTarget, Subject, and a few others that don't run on a "reference" like the PlayerRef just become "null reference" meaning they won't actually trigger the dialogue.

**Comment by Noggog** [comment]
Can you show the unexpected changes/output with an xEdit screenshot?

**Comment by HDMFanatic** [comment]
[https://imgur.com/a/Fnttg6k](url)

Here are a few examples (I'm using xEdit's hide empty and non-conflicting rows feature).

You can see that anything that refers to "PlayerRef" copies correctly but other flags don't. i.e. Target.HasKeyword gets copied as NULL REFERENCE.HasKeyword.

**Comment by Noggog** [comment]
Cool, i see what you're seeing
![image](https://github.com/Synthesis-Collective/RaceCompatibilityDialogue/assets/24981326/27baa775-e6fe-4551-9b21-d6a173e088f7)

And I also see in the code where this is occurring.  However, I'm not the original author, and so am decently unfamiliar with its goals and what it "should" be trying to do instead.  Do you know what the desired output is in the picture I posted?

Should the Condition 4 be removed entirely?  Or should the NULL be set to something else?  If so, what?

**Comment by HDMFanatic** [comment]
By my understanding both Condition 1 and Condition 4 should be set to "Subject" in the pictured example.

Thus meaning any time "Target" and "Combat Target" are flagged it should be flagged respectively for the Proxy keywords.

**Comment by HDMFanatic** [comment]
At a glance, it seems like one thing was fixed but the other two still aren't addressed properly.
![2023-07-21_18-35-42](https://github.com/Synthesis-Collective/RaceCompatibilityDialogue/assets/139965078/e86e488e-0eb0-4a25-83e1-1058172afed0)
![2023-07-21_18-40-37](https://github.com/Synthesis-Collective/RaceCompatibilityDialogue/assets/139965078/4bf1abc7-d038-49ef-962d-d79ea3782e60)

The NULL REFERENCE is fixed, but instead of the Combat Target and Target flags being used it's all using the Subject flag. Now this could be because of my poor wording of what the expected output should be before you changed the code to achieve this result, and if so my apologies.

**Comment by Noggog** [comment]
Alright, try again.  If you've got `Auto` selected it should update to `31191e` and get the new stuff

**Comment by HDMFanatic** [comment]
Last thing that needs to be adjusted seems to be the "Subject.GetPCIsRace" condition. That one will have to use the PlayerRef (which it had been doing before you added the new flag checks), because I see no way to get the PC Proxy Keyword without using the PlayerRef.

**Comment by HDMFanatic** [comment]
Oh, I forgot to screenshot what I mentioned in my last comment.
![2023-07-22_21-23-33](https://github.com/Synthesis-Collective/RaceCompatibilityDialogue/assets/139965078/9add7ad2-7a6a-4499-bfbc-f35fec3aa517)
All of the conditions here are running on the Subject, but the conditions are looking for the Player's Race. I do see an instance in the code where the "GetPCIsRace" condition is mentioned but I'm not sure how you'd go about making that check provide the "PlayerRef.HasKeyword=ActorProxyX" with the current set-up.

**Comment by Noggog** [comment]
Sorry, getting caught up in other stuff, and getting a bit out of my depth without sinking in some research time.  Perhaps @mrudat can pick it up from here

**Comment by Noggog** [comment]
@HDMFanatic Someone else put up a potential fix over in #15.  

IF you get a few, can you test that it addresses your concerns?  You can easily swap to the test code by adjusting your patcher to point to https://github.com/BitterlyIronic/RaceCompatibilityDialogue instead of the normal address.

**Comment by HDMFanatic** [comment]
Looks like that does the trick from my checking through xEdit at a handful of dialogue topics. I thought there were issues regarding some conditions incorrectly using "AND" instead of "OR" but those were cases where the condition was making sure the player _wasn't_ a particular race. Like Rolff Stone-Fist being rude to everyone except Nords. So those cases are actually totally fine.
