### ISSUE TITLE
Reduces TIFC to number of patched Topic Info

### ISSUE THREAD

**Issue by reissue1426** [Synthesis-Collective/RaceCompatibilityDialogue#18]
The patcher seems to change the Info Count (TIFC) to the number of INFO records in that topic that the patcher made changes to. Based on [what uesp says](https://en.uesp.net/wiki/Skyrim_Mod:Mod_File_Format/DIAL) about TIFC it probably doesn't matter?
![image](https://github.com/user-attachments/assets/7c60e370-ee9c-45f0-a0ee-e70bbe385d69)

**Comment by Noggog** [comment]
This is a side effect of [Mutagen](https://github.com/Mutagen-Modding/Mutagen)'s systems.  TIFC is a "derivative" item, eg, it's automatically populated by the amount of `Info`s in the list.  So when it parses that record it just reads in the `2` Infos, it doesn't -also- save the `7` somewhere to export on the other side.   When it goes to export, it has two infos on the list and puts `2` into the TIFC.

This shouldnt be a problem, as `2` is probably more accurate value?  If not, and it's causing issues, definitely gather any info and open a card on [Mutagen](https://github.com/Mutagen-Modding/Mutagen)'s repo with the details
